name: client_server_lan
description: A simple to use LAN communication package. The Server and a Client
  can freely distribute data over LAN.
version: 3.0.1
homepage: https://github.com/Robert3141/client_server_lan

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter:

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  emodebug: ^0.5.0
  meta: ^1.2.4
  isohttpd: ^0.5.0
  get_ip: ^0.4.0

dev_dependencies:
  pedantic: ^1.9.2
