name: client_server_lan
description: A simple to use LAN communication package. The Server and a Client can freely distribute data over LAN.
version: 1.0.2
homepage: https://github.com/Robert3141/client_server_lan

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  isohttpd: ^0.4.0
  meta: ^1.1.8
  emodebug: ^0.4.0