name: client_server_lan
description: A simple to use LAN communication package. The Server and a Client
  can freely distribute data over LAN.
version: 2.0.1
homepage: https://github.com/Robert3141/client_server_lan

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  emodebug: ^0.5.0
  isohttpd: ^0.5.0
  meta: ^1.3.0
  wifi: ^0.1.4
