name: client_server_lan
description: A simple to use LAN communication package. A Server and a Client can be setup. Then the server broadcasts itself and connects to any listening clients. Data can then be transferred between each. The server and client can then disconnect when ready.
version: 0.0.2
homepage: https://github.com/Robert3141/client_server_lan

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  uuid: ^2.0.4
  dio: ^3.0.9
  meta: ^1.1.8
  prompts: ^1.3.1
  emodebug: ^0.4.0
  isohttpd: ^0.4.0
  err: ^0.9.0